// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/janghanul090801/spine-clean-architecture/domain"
	mock "github.com/stretchr/testify/mock"
)

// AuthUseCase is an autogenerated mock type for the AuthUseCase type
type AuthUseCase struct {
	mock.Mock
}

// CreateAccessAndRefreshToken provides a mock function with given fields: c, user
func (_m *AuthUseCase) CreateAccessAndRefreshToken(c context.Context, user *domain.User) (string, string, error) {
	ret := _m.Called(c, user)

	if len(ret) == 0 {
		panic("no return value specified for CreateAccessAndRefreshToken")
	}

	var r0 string
	var r1 string
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.User) (string, string, error)); ok {
		return rf(c, user)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domain.User) string); ok {
		r0 = rf(c, user)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *domain.User) string); ok {
		r1 = rf(c, user)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(context.Context, *domain.User) error); ok {
		r2 = rf(c, user)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// ExtractUserFromRefreshToken provides a mock function with given fields: c, requestToken
func (_m *AuthUseCase) ExtractUserFromRefreshToken(c context.Context, requestToken string) (*domain.User, error) {
	ret := _m.Called(c, requestToken)

	if len(ret) == 0 {
		panic("no return value specified for ExtractUserFromRefreshToken")
	}

	var r0 *domain.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.User, error)); ok {
		return rf(c, requestToken)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.User); ok {
		r0 = rf(c, requestToken)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(c, requestToken)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Login provides a mock function with given fields: c, email, password
func (_m *AuthUseCase) Login(c context.Context, email string, password string) (*domain.User, error) {
	ret := _m.Called(c, email, password)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 *domain.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*domain.User, error)); ok {
		return rf(c, email, password)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *domain.User); ok {
		r0 = rf(c, email, password)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(c, email, password)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Register provides a mock function with given fields: c, name, email, password
func (_m *AuthUseCase) Register(c context.Context, name string, email string, password string) (*domain.User, error) {
	ret := _m.Called(c, name, email, password)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 *domain.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) (*domain.User, error)); ok {
		return rf(c, name, email, password)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) *domain.User); ok {
		r0 = rf(c, name, email, password)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = rf(c, name, email, password)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewAuthUseCase creates a new instance of AuthUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuthUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuthUseCase {
	mock := &AuthUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
