// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/janghanul090801/spine-clean-architecture/domain"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// TaskUseCase is an autogenerated mock type for the TaskUseCase type
type TaskUseCase struct {
	mock.Mock
}

// Create provides a mock function with given fields: c, task, userID
func (_m *TaskUseCase) Create(c context.Context, task *domain.Task, userID *uuid.UUID) (*domain.Task, error) {
	ret := _m.Called(c, task, userID)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *domain.Task
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Task, *uuid.UUID) (*domain.Task, error)); ok {
		return rf(c, task, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Task, *uuid.UUID) *domain.Task); ok {
		r0 = rf(c, task, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Task)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *domain.Task, *uuid.UUID) error); ok {
		r1 = rf(c, task, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FetchByUserID provides a mock function with given fields: c, userID
func (_m *TaskUseCase) FetchByUserID(c context.Context, userID *uuid.UUID) ([]*domain.Task, error) {
	ret := _m.Called(c, userID)

	if len(ret) == 0 {
		panic("no return value specified for FetchByUserID")
	}

	var r0 []*domain.Task
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *uuid.UUID) ([]*domain.Task, error)); ok {
		return rf(c, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *uuid.UUID) []*domain.Task); ok {
		r0 = rf(c, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Task)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *uuid.UUID) error); ok {
		r1 = rf(c, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewTaskUseCase creates a new instance of TaskUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTaskUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *TaskUseCase {
	mock := &TaskUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
